# Generated by Django 3.2 on 2021-04-26 16:35

import datetime

import django.db.models.deletion
from django.db import migrations
from django.db import models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Budget name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category name')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budget', to='snaver.budget')),
            ],
        ),
        migrations.CreateModel(
            name='MockUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='User name')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Subcategory name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_category', to='snaver.category')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Transaction name')),
                ('payee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Payee name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('receipt_date', models.DateField(verbose_name='Receipt date')),
                ('created_timestamp', models.DateField(default=datetime.datetime(2021, 4, 26, 16, 35, 5, 567174, tzinfo=utc), verbose_name='Receipt timestamp')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_subcategory', to='snaver.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_user', to='snaver.mockuser'),
        ),
    ]
