# Generated by Django 3.2 on 2021-06-04 19:22

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('snaver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='inflow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='outflow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11),
        ),
    ]
