# Generated by Django 3.2 on 2021-05-05 18:56

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('snaver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorydetails',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='snaver.subcategory'),
        ),
    ]
