# Generated by Django 3.2 on 2021-05-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snaver', '0002_alter_subcategorydetails_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategorydetails',
            old_name='details',
            new_name='subcategory',
        ),
    ]
