# Generated by Django 3.2 on 2021-06-04 19:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('snaver', '0003_auto_20210604_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='inflow',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='outflow',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
