# Generated by Django 3.2 on 2021-06-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snaver', '0004_auto_20210604_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='inflow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='outflow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
