# Generated by Django 3.2 on 2021-06-20 20:21

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('snaver', '0005_auto_20210604_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorydetails',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_details', to='snaver.subcategory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='inflow',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='outflow',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True),
        ),
    ]
