# Generated by Django 3.2 on 2021-06-27 08:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('snaver', '0006_auto_20210627_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=100000),
        ),
    ]
