# Generated by Django 3.2 on 2021-06-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snaver', '0006_auto_20210620_2221'),
        ('snaver', '0007_category_order'),
    ]

    operations = [
    ]
