# Generated by Django 3.2 on 2021-06-27 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snaver', '0008_merge_0006_auto_20210620_2221_0007_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='order',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='subcategorydetails',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='snaver.subcategory'),
        ),
    ]
